### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by ElisabetRD** [SistemasTecTlaxiaco/actividad-1-infografia-ElisabetRD#2]
[Ciclos de vida del desarrollo de software (1).pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-ElisabetRD/files/9420118/Ciclos.de.vida.del.desarrollo.de.software.1.pdf)

**Comment by IrvingFernand0** [comment]
Calificación: 17

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
